version: "3.8"
services:
  nifi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi
    restart: always
    ports:
      - 8085:8085
    environment:
      - NIFI_WEB_HTTP_PORT=8085
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin
    volumes:
      - ./data:/opt/nifi/data
      - ./database_repository:/opt/nifi/nifi-current/database_repository
      - ./properties:/opt/nifi/nifi-current/properties
      - ./flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./content_repository:/opt/nifi/nifi-current/content_repository
      - ./provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ./lib:/opt/nifi/nifi-current/extensions
      - ./state:/opt/nifi/nifi-current/state
      - ./logs:/opt/nifi/nifi-current/logs
      # (IMPORTANT) first docker compose without mount, than copy the container /opt/nifi/nifi-current/conf inside ./conf , docker compose down & up
      # example : docker cp container_id:/opt/nifi/nifi-current/conf/ ./conf && docker-compose down && docker compose up -d
      # - ./conf:/opt/nifi/nifi-current/conf
      - ./drivers:/opt/nifi/drivers
    networks:
      - nifi_network

  nifi-registry:
    image: apache/nifi-registry:latest
    container_name: nifi-registry
    restart: always
    ports:
      - 18080:18080
    volumes:
      - "./nifi-registry/data:/data"
      - "./nifi-registry/database:/opt/nifi-registry/nifi-registry-current/database"
      - "./nifi-registry/flow_storage:/opt/nifi-registry/nifi-registry-current/flow_storage"
    environment:
      - NIFI_REGISTRY_WEB_HTTP_PORT=18080
      - NIFI_REGISTRY_DB_DIR=/opt/nifi-registry/nifi-registry-current/database
      - NIFI_REGISTRY_FLOW_PROVIDER=file
      - NIFI_REGISTRY_FLOW_STORAGE_DIR=/opt/nifi-registry/nifi-registry-current/flow_storage
    networks:
      - nifi_network

networks:
  nifi_network:
    driver: bridge
